### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "joh@gmail.com",
  "address": "india",
  "dateOfBirth": "2005-12-07",
  "registerdDate": "2020-12-04"

}

###