server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            ## http://localhost:4004/auth/login
            ## API Gateway -> http://auth-service:4005/login
            - id: auth-service-route
              uri: http://auth-service:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1



            # REST CLIENT -> http://localhost:4004/api/patients
            # API GATEWAY -> http://patient-service:4000/patients   // strip removes -> /api
            # PATIENT SERVICE (SPRING BOOT APP) -> /patients -> Patients Array (Returned)
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1

            # REST CLIENT -> http://localhost:4004/api-docs/patients
            # API-GATEWAY -> http://patient-service:4000/v3/api-docs
            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients, /v3/api-docs
