spring.application.name=patient-service
server.port=4000

spring.kafka.bootstrap-servers=localhost:9092

#here we're telling spring that our messages are going to have string key & value as bytearray.
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer